name: aeriemed
description: AerieMed - Private Medical Protocols Library
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  pdfrx: ^2.4.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.0
  file_picker: ^8.0.0
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png/icon.png.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/protocols/
