import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'ics206wf_form.dart' show Ics206WfData, Ics206WfSeverity;

const _kAccent = PdfColors.red800;
const _kAccentLight = PdfColors.red50;
const _kGrid = PdfColors.grey300;

final _sH1 = pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: _kAccent);
final _sH2 = pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white);
const _sBody = pw.TextStyle(fontSize: 9);
const _sSmall = pw.TextStyle(fontSize: 8, color: PdfColors.grey700);
final _sLabelCell = pw.TextStyle(fontSize: 8, color: PdfColors.grey600, fontWeight: pw.FontWeight.bold);

Future<Uint8List> buildIcs206WfPdf(Ics206WfData f) async {
  final doc = pw.Document(title: '8-Line/206WF Medical Incident Report', creator: 'ResQruck');

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.letter,
      margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 36),
      header: (_) => _pageHeader(),
      footer: (ctx) => _pageFooter(ctx),
      build: (_) => _buildContent(f),
    ),
  );

  return doc.save();
}

pw.Widget _pageHeader() => pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(color: _kAccent, width: 1.5)),
      ),
      padding: const pw.EdgeInsets.only(bottom: 6),
      child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
        pw.Text('8-Line/206WF Medical Incident Report', style: _sH1),
        pw.SizedBox(height: 2),
        pw.Text('ICS-206 WF (03/18) — Reference/fillable checklist for calling in a medical emergency or resource request over radio.', style: _sSmall),
      ]),
    );

pw.Widget _pageFooter(pw.Context ctx) => pw.Container(
      margin: const pw.EdgeInsets.only(top: 6),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
      ),
      padding: const pw.EdgeInsets.only(top: 4),
      child: pw.Row(children: [
        pw.Text('Generated by ResQruck', style: _sSmall),
        pw.Spacer(),
        pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}', style: _sSmall),
      ]),
    );

String _severityLabel(Ics206WfSeverity s) => switch (s) {
      Ics206WfSeverity.red => 'RED / PRIORITY 1 — Life or limb threatening. Evacuation need is IMMEDIATE.',
      Ics206WfSeverity.yellow => 'YELLOW / PRIORITY 2 — Serious injury or illness. Evacuation may be DELAYED if necessary.',
      Ics206WfSeverity.green => 'GREEN / PRIORITY 3 — Minor injury or illness. Non-emergency transport.',
      Ics206WfSeverity.none => 'Not specified',
    };

List<pw.Widget> _buildContent(Ics206WfData f) {
  return [
    _sectionHead('SEVERITY OF EMERGENCY / TRANSPORT PRIORITY'),
    _bodyText(_severityLabel(f.severity)),
    _gap,

    _sectionHead('INCIDENT DETAILS'),
    _labelValueTable([
      ['Nature of Injury/Illness', f.natureOfInjury],
      ['Evacuation Request', f.evacuationRequest],
      ['Patient Location', f.patientLocation],
      ['Incident Name', f.incidentName],
      ['On-Scene IC', f.onSceneIc],
      ['Patient Care', f.patientCare],
    ]),
    _gap,

    _sectionHead('INITIAL PATIENT ASSESSMENT'),
    if (f.patients.isEmpty)
      _bodyText('(none documented)')
    else
      pw.Column(children: [
        for (var i = 0; i < f.patients.length; i++) ...[
          if (i > 0) pw.SizedBox(height: 6),
          pw.Text('Patient ${i + 1}', style: _sLabelCell),
          _labelValueTable([
            ['Assessment', f.patients[i].assessment],
            ['Treatment', f.patients[i].treatment],
          ]),
        ],
      ]),
    _gap,

    _sectionHead('EVACUATION PLAN'),
    _labelValueTable([
      ['Evacuation Location', f.evacLocation],
      ["Patient ETA", f.patientEta],
      ['Helispot/Extraction Hazards', f.helispotHazards],
    ]),
    _gap,

    _sectionHead('ADDITIONAL RESOURCES / EQUIPMENT NEEDS'),
    _bodyText(f.additionalResources.isEmpty ? '(none documented)' : f.additionalResources),
    _gap,

    _sectionHead('COMMUNICATIONS'),
    _commsTable(f),
    _gap,

    _sectionHead('CONTINGENCY'),
    _bodyText(f.contingency.isEmpty ? '(none documented)' : f.contingency),
    _gap,

    _sectionHead('ADDITIONAL INFORMATION'),
    _bodyText(f.additionalInfo.isEmpty ? '(none documented)' : f.additionalInfo),
  ];
}

final _gap = pw.SizedBox(height: 12);

pw.Widget _sectionHead(String title) => pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 3),
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      decoration: const pw.BoxDecoration(color: _kAccent),
      child: pw.Text(title, style: _sH2),
    );

pw.Widget _bodyText(String text) => pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      child: pw.Text(text.isEmpty ? '—' : text, style: _sBody),
    );

pw.Widget _lbl(String s) => pw.Container(
      color: _kAccentLight,
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      child: pw.Text(s, style: _sLabelCell),
    );

pw.Widget _val(String s) => pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
      child: pw.Text(s.isEmpty ? '—' : s, style: _sBody),
    );

pw.Widget _labelValueTable(List<List<String>> rows) => pw.Table(
      border: pw.TableBorder.all(color: _kGrid, width: 0.5),
      columnWidths: const {0: pw.FlexColumnWidth(1.3), 1: pw.FlexColumnWidth(2.4)},
      children: rows.map((r) => pw.TableRow(children: [_lbl(r[0]), _val(r[1])])).toList(),
    );

pw.Widget _commsTable(Ics206WfData f) {
  pw.Widget hdr(String s) => pw.Container(
        color: _kAccent,
        padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
        child: pw.Text(s, style: pw.TextStyle(fontSize: 7, fontWeight: pw.FontWeight.bold, color: PdfColors.white), textAlign: pw.TextAlign.center),
      );
  pw.Widget cell(String s) => pw.Container(
        padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
        child: pw.Text(s.isEmpty ? '—' : s, style: _sSmall, textAlign: pw.TextAlign.center),
      );

  final rows = [
    ['COMMAND', f.commandChannel, f.commandRx, f.commandRxTone, f.commandTx, f.commandTxTone],
    ['AIR-TO-GRND', f.airGrndChannel, f.airGrndRx, f.airGrndRxTone, f.airGrndTx, f.airGrndTxTone],
    ['TACTICAL', f.tacticalChannel, f.tacticalRx, f.tacticalRxTone, f.tacticalTx, f.tacticalTxTone],
  ];

  return pw.Table(
    border: pw.TableBorder.all(color: _kGrid, width: 0.5),
    columnWidths: const {
      0: pw.FlexColumnWidth(1.3),
      1: pw.FlexColumnWidth(1.6),
      2: pw.FlexColumnWidth(1.1),
      3: pw.FlexColumnWidth(1.1),
      4: pw.FlexColumnWidth(1.1),
      5: pw.FlexColumnWidth(1.1),
    },
    children: [
      pw.TableRow(children: [
        hdr(''), hdr('Channel Name/Number'), hdr('RX'), hdr('RX Tone/NAC'), hdr('TX'), hdr('TX Tone/NAC'),
      ]),
      ...rows.map((r) => pw.TableRow(children: [
            pw.Container(
              color: _kAccentLight,
              padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
              child: pw.Text(r[0], style: _sLabelCell, textAlign: pw.TextAlign.center),
            ),
            cell(r[1]), cell(r[2]), cell(r[3]), cell(r[4]), cell(r[5]),
          ])),
    ],
  );
}
